
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 2026 
-- Modulo: consultas (JSON anamnesis + resumen)
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.consultas.api',
      p_base_path      => '/api/consultas/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.consultas.api',
      p_pattern        => 'resumen',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.consultas.api',
      p_pattern        => 'resumen',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT id_consulta,
       fecha_atencion,
       motivo_principal,
       sintomas,
       motivo_consulta,
       paciente,
       medico
FROM v_consultas_resumen');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.consultas.api',
      p_pattern        => 'diagnosticos-frecuentes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.consultas.api',
      p_pattern        => 'diagnosticos-frecuentes',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT codigo_cie, descripcion, total_diagnosticos
FROM v_diagnosticos_frecuentes
FETCH FIRST 10 ROWS ONLY');

        
COMMIT;

END;
