
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 06:16:56 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.api.citas',
      p_base_path      => '/api/citas/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-mes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-mes',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT TO_CHAR(TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), ''YYYY-MM'') AS mes,
       e.codigo AS estado,
       COUNT(*) AS total_citas
FROM cita c
JOIN estado_cita e ON e.id_estado = c.id_estado
GROUP BY ROLLUP (TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), e.codigo)
ORDER BY mes, estado');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'promedio-cita',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'promedio-cita',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH citas_diarias AS (
  SELECT TRUNC(CAST(c.fecha_hora AS DATE)) AS fecha,
         COUNT(*) AS total
  FROM cita c
  GROUP BY TRUNC(CAST(c.fecha_hora AS DATE))
)
SELECT fecha,
       total,
       ROUND(AVG(total) OVER (ORDER BY fecha ROWS BETWEEN 6 PRECEDING AND CURRENT ROW), 2) AS avg_7d
FROM citas_diarias
ORDER BY fecha');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-estado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-estado',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH base AS (
  SELECT TO_CHAR(TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), ''YYYY-MM'') AS mes,
         e.codigo AS estado
  FROM cita c
  JOIN estado_cita e ON e.id_estado = c.id_estado
)
SELECT *
FROM base
PIVOT (
  COUNT(*) FOR estado IN (
    ''PROGRAMADA'' AS programada,
    ''ATENDIDA'' AS atendida,
    ''CANCELADA'' AS cancelada
  )
)
ORDER BY mes');

    
        
COMMIT;

END;