
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 06:19:02 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.recetas.api',
      p_base_path      => '/api/recetas/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.recetas.api',
      p_pattern        => 'medicamentos-mas-recetados',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.recetas.api',
      p_pattern        => 'medicamentos-mas-recetados',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH det AS (
  SELECT TO_CHAR(TRUNC(CAST(r.fecha_emision AS DATE), ''MM''), ''YYYY-MM'') AS mes,
         m.nombre_generico AS medicamento,
         COUNT(*) AS total
  FROM receta r
  JOIN receta_detalle rd ON rd.id_receta = r.id_receta
  JOIN medicamento m ON m.id_medicamento = rd.id_medicamento
  GROUP BY TRUNC(CAST(r.fecha_emision AS DATE), ''MM''), m.nombre_generico
)
SELECT *
FROM (
  SELECT mes,
         medicamento,
         total,
         ROW_NUMBER() OVER (PARTITION BY mes ORDER BY total DESC) AS rn
  FROM det
)
WHERE rn <= 5
ORDER BY mes, total DESC');

    
        
COMMIT;

END;