
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 06:19:31 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_base_path      => '/api/pacientes/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'promedio-atencion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'promedio-atencion',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH espera AS (
  SELECT c.id_cita,
         c.id_paciente,
         c.fecha_hora,
         con.fecha_atencion,
         (CAST(con.fecha_atencion AS DATE) - CAST(c.fecha_hora AS DATE)) * 24 * 60 AS espera_min
  FROM cita c
  JOIN consulta con ON con.id_cita = c.id_cita AND con.fecha_cita = c.fecha_hora
  WHERE con.fecha_atencion IS NOT NULL
)
SELECT *
FROM (
  SELECT id_paciente,
         ROUND(AVG(espera_min), 2) AS espera_prom_min,
         PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY espera_min) AS p95_espera_min
  FROM espera
  GROUP BY id_paciente
  ORDER BY espera_prom_min DESC
)
FETCH FIRST 20 ROWS ONLY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'brachas-citas-paciente',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'brachas-citas-paciente',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH citas_paciente AS (
  SELECT id_paciente,
         fecha_hora,
         LAG(fecha_hora) OVER (PARTITION BY id_paciente ORDER BY fecha_hora) AS fecha_prev
  FROM cita
)
SELECT id_paciente,
       MAX(CAST(fecha_hora AS DATE) - CAST(fecha_prev AS DATE)) AS max_gap_dias
FROM citas_paciente
WHERE fecha_prev IS NOT NULL
GROUP BY id_paciente
ORDER BY max_gap_dias DESC
FETCH FIRST 20 ROWS ONLY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'ultima-consulta-paciente',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'ultima-consulta-paciente',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT p.id_persona AS id_paciente,
       p.apellidos || '', '' || p.nombres AS paciente,
       lc.id_consulta,
       lc.fecha_atencion,
       lc.motivo_consulta
FROM persona p
JOIN paciente pa ON pa.id_paciente = p.id_persona
OUTER APPLY (
  SELECT con.id_consulta,
         con.fecha_atencion,
         con.motivo_consulta
  FROM consulta con
  JOIN cita c ON c.id_cita = con.id_cita AND c.fecha_hora = con.fecha_cita
  WHERE c.id_paciente = pa.id_paciente
  ORDER BY con.fecha_atencion DESC
  FETCH FIRST 1 ROW ONLY
) lc
WHERE UPPER(p.nombres || '' '' || p.apellidos) LIKE ''%'' || UPPER(''&nombre_paciente'') || ''%''
ORDER BY p.id_persona');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'paciente-promedio-satisfaccion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'paciente-promedio-satisfaccion',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH uso AS (
  SELECT c.id_paciente,
         COUNT(*) AS total_citas
  FROM cita c
  GROUP BY c.id_paciente
), stats AS (
  SELECT AVG(total_citas) AS avg_citas,
         STDDEV(total_citas) AS sd_citas
  FROM uso
)
SELECT p.apellidos || '', '' || p.nombres AS paciente,
       u.total_citas,
       ROUND((u.total_citas - s.avg_citas) / NULLIF(s.sd_citas, 0), 2) AS z_score
FROM uso u
CROSS JOIN stats s
JOIN persona p ON p.id_persona = u.id_paciente
ORDER BY z_score DESC NULLS LAST
FETCH FIRST 20 ROWS ONLY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'rank-alergias',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'rank-alergias',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM (
  SELECT a.categoria,
         a.nombre,
         pa.severidad,
         COUNT(*) AS total,
         ROW_NUMBER() OVER (PARTITION BY a.categoria, pa.severidad ORDER BY COUNT(*) DESC) AS rn
  FROM paciente_alergia pa
  JOIN alergeno a ON a.id_alergeno = pa.id_alergeno
  GROUP BY a.categoria, a.nombre, pa.severidad
)
WHERE rn <= 5
ORDER BY categoria, severidad, total DESC');

    
        
COMMIT;

END;