
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 11:02:15 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_base_path      => '/api/pacientes/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'promedio-atencion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'promedio-atencion',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH espera AS (
  SELECT c.id_cita,
         c.id_paciente,
         c.fecha_hora,
         con.fecha_atencion,
         (CAST(con.fecha_atencion AS DATE) - CAST(c.fecha_hora AS DATE)) * 24 * 60 AS espera_min
  FROM cita c
  JOIN consulta con ON con.id_cita = c.id_cita AND con.fecha_cita = c.fecha_hora
  WHERE con.fecha_atencion IS NOT NULL
)
SELECT *
FROM (
  SELECT e.id_paciente,
         p.apellidos || '', '' || p.nombres AS paciente,
         ROUND(AVG(e.espera_min), 2) AS espera_prom_min,
         PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY e.espera_min) AS p95_espera_min
  FROM espera e
  JOIN persona p ON p.id_persona = e.id_paciente
  GROUP BY e.id_paciente, p.apellidos, p.nombres
  ORDER BY espera_prom_min DESC
)
FETCH FIRST 20 ROWS ONLY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'brachas-citas-paciente',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'brachas-citas-paciente',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH citas_paciente AS (
  SELECT id_paciente,
         fecha_hora,
         LAG(fecha_hora) OVER (PARTITION BY id_paciente ORDER BY fecha_hora) AS fecha_prev
  FROM cita
)
SELECT cp.id_paciente,
       p.apellidos || '', '' || p.nombres AS paciente,
       MAX(CAST(cp.fecha_hora AS DATE) - CAST(cp.fecha_prev AS DATE)) AS max_gap_dias
FROM citas_paciente cp
JOIN persona p ON p.id_persona = cp.id_paciente
WHERE cp.fecha_prev IS NOT NULL
GROUP BY cp.id_paciente, p.apellidos, p.nombres
ORDER BY max_gap_dias DESC
FETCH FIRST 20 ROWS ONLY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'ultima-consulta-paciente',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'ultima-consulta-paciente',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT p.id_persona AS id_paciente,
       p.apellidos || '', '' || p.nombres AS paciente,
       lc.id_consulta,
       lc.fecha_atencion,
       lc.motivo_consulta
FROM persona p
JOIN paciente pa ON pa.id_paciente = p.id_persona
OUTER APPLY (
  SELECT con.id_consulta,
         con.fecha_atencion,
         con.motivo_consulta
  FROM consulta con
  JOIN cita c ON c.id_cita = con.id_cita AND c.fecha_hora = con.fecha_cita
  WHERE c.id_paciente = pa.id_paciente
  ORDER BY con.fecha_atencion DESC
  FETCH FIRST 1 ROW ONLY
) lc
WHERE UPPER(p.nombres || '' '' || p.apellidos) LIKE ''%'' || UPPER(''&nombre_paciente'') || ''%''
ORDER BY p.id_persona');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'paciente-promedio-satisfaccion',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'paciente-promedio-satisfaccion',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH uso AS (
  SELECT c.id_paciente,
         COUNT(*) AS total_citas
  FROM cita c
  GROUP BY c.id_paciente
), stats AS (
  SELECT AVG(total_citas) AS avg_citas,
         STDDEV(total_citas) AS sd_citas
  FROM uso
)
SELECT p.apellidos || '', '' || p.nombres AS paciente,
       u.total_citas,
       ROUND((u.total_citas - s.avg_citas) / NULLIF(s.sd_citas, 0), 2) AS z_score
FROM uso u
CROSS JOIN stats s
JOIN persona p ON p.id_persona = u.id_paciente
ORDER BY z_score DESC NULLS LAST
FETCH FIRST 20 ROWS ONLY');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'rank-alergias',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'rank-alergias',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM (
  SELECT a.categoria,
         a.nombre,
         pa.severidad,
         COUNT(*) AS total,
         ROW_NUMBER() OVER (PARTITION BY a.categoria, pa.severidad ORDER BY COUNT(*) DESC) AS rn
  FROM paciente_alergia pa
  JOIN alergeno a ON a.id_alergeno = pa.id_alergeno
  GROUP BY a.categoria, a.nombre, pa.severidad
)
WHERE rn <= 5
ORDER BY categoria, severidad, total DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'create',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'create',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_body         CLOB := :body_text;
    l_id_paciente  NUMBER;
BEGIN
    sp_registrar_paciente(
        p_cedula                       => JSON_VALUE(l_body, ''$.cedula''),
        p_nombres                      => JSON_VALUE(l_body, ''$.nombres''),
        p_apellidos                    => JSON_VALUE(l_body, ''$.apellidos''),
        p_fecha_nacimiento             => TO_DATE(JSON_VALUE(l_body, ''$.fecha_nacimiento''), ''YYYY-MM-DD''),
        p_sexo                         => JSON_VALUE(l_body, ''$.sexo''),
        p_email                        => JSON_VALUE(l_body, ''$.email''),
        p_historia_clinica             => JSON_VALUE(l_body, ''$.historia_clinica''),
        p_tipo_sangre                  => JSON_VALUE(l_body, ''$.tipo_sangre''),
        p_factor_rh                    => JSON_VALUE(l_body, ''$.factor_rh''),
        p_ocupacion                    => JSON_VALUE(l_body, ''$.ocupacion''),
        p_estado_civil                 => JSON_VALUE(l_body, ''$.estado_civil''),
  ' || '      p_contacto_emergencia_nombre   => JSON_VALUE(l_body, ''$.contacto_emergencia_nombre''),
        p_contacto_emergencia_telefono => JSON_VALUE(l_body, ''$.contacto_emergencia_telefono''),
        p_numero_telefono              => JSON_VALUE(l_body, ''$.numero_telefono''),
        p_tipo_telefono                => JSON_VALUE(l_body, ''$.tipo_telefono''),
        p_id_parroquia                 => JSON_VALUE(l_body, ''$.id_parroquia'' RETURNING NUMBER),
        p_calle_principal              => JSON_VALUE(l_body, ''$.calle_principal''),
        p_calle_secundaria             => JSON_VALUE(l_body, ''$.calle_secundaria''),
        p_numeracion                   => JSON_VALUE(l_body, ''$.numeracion''),
        p_referencia                   => JSON_VALUE(l_body, ''$.referencia''),
        p_id_paciente                  => l_id_paciente
    );

    :status_code := 201;

    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Content-Type: application/json'');
    OWA_UTIL.http_header' || '_close;

    HTP.prn(
        JSON_OBJECT(
            ''mensaje'' VALUE ''Paciente registrado correctamente'',
            ''id_paciente'' VALUE l_id_paciente
        )
    );
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        :status_code := 400;

        OWA_UTIL.mime_header(''application/json'', FALSE);
        HTP.p(''Content-Type: application/json'');
        OWA_UTIL.http_header_close;

        HTP.prn(
            JSON_OBJECT(
                ''mensaje'' VALUE ''Error al registrar paciente'',
                ''codigo'' VALUE SQLCODE,
                ''detalle'' VALUE SQLERRM
            )
        );
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'listar',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.pacientes.api',
      p_pattern        => 'listar',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT pa.historia_clinica AS expediente,
       p.nombres || '' '' || p.apellidos AS paciente,
       p.cedula,
       TO_CHAR(MAX(c.fecha_hora), ''DD Mon, YYYY'', ''NLS_DATE_LANGUAGE=SPANISH'') AS ultima_cita,
       CASE
         WHEN SUM(CASE
                    WHEN ec.codigo = ''PROGRAMADA''
                     AND c.fecha_hora > SYSDATE THEN 1
                    ELSE 0
                  END) > 0 THEN ''Pendiente''
         WHEN MAX(c.fecha_hora) >= ADD_MONTHS(TRUNC(SYSDATE), -12) THEN ''Al dia''
         WHEN MAX(c.fecha_hora) IS NULL THEN ''Sin citas''
         ELSE ''Inactivo''
       END AS estado
FROM paciente pa
JOIN persona p ON p.id_persona = pa.id_paciente
LEFT JOIN cita c ON c.id_paciente = pa.id_paciente
LEFT JOIN estado_cita ec ON ec.id_estado = c.id_estado
GROUP BY pa.historia_clinica,
         p.nombres,
         p.apellidos,
         p.cedula
ORDER BY paciente');

    
        
COMMIT;

END;