
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 06:19:18 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.medicos.api',
      p_base_path      => '/api/medicos/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'citas-rank',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'citas-rank',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM (
  SELECT m.id_medico,
         p.apellidos || '', '' || p.nombres AS medico,
         COUNT(*) AS total_citas,
         DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS rnk
  FROM cita c
  JOIN medico m ON m.id_medico = c.id_medico
  JOIN persona p ON p.id_persona = m.id_medico
  GROUP BY m.id_medico, p.apellidos, p.nombres
)
WHERE rnk <= 10
ORDER BY total_citas DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'citas-especialidad',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'citas-especialidad',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT e.nombre AS especialidad,
       TO_CHAR(TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), ''YYYY-MM'') AS mes,
       COUNT(*) AS total
FROM cita c
JOIN medico_especialidad me ON me.id_medico = c.id_medico
JOIN especialidad e ON e.id_especialidad = me.id_especialidad
GROUP BY GROUPING SETS (
  (e.nombre, TRUNC(CAST(c.fecha_hora AS DATE), ''MM'')),
  (e.nombre),
  (TRUNC(CAST(c.fecha_hora AS DATE), ''MM''))
)
ORDER BY especialidad, mes');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'diagnosticos-rank',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'diagnosticos-rank',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM (
  SELECT c.id_medico,
         cd.codigo_cie,
         COUNT(*) AS total,
         DENSE_RANK() OVER (PARTITION BY c.id_medico ORDER BY COUNT(*) DESC) AS rnk
  FROM consulta con
  JOIN cita c ON c.id_cita = con.id_cita AND c.fecha_hora = con.fecha_cita
  JOIN consulta_diagnostico cd ON cd.id_consulta = con.id_consulta
  GROUP BY c.id_medico, cd.codigo_cie
)
WHERE rnk <= 3
ORDER BY id_medico, total DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'especialidad-estado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.medicos.api',
      p_pattern        => 'especialidad-estado',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT e.nombre AS especialidad,
       ec.codigo AS estado,
       COUNT(*) AS total
FROM cita c
JOIN medico_especialidad me ON me.id_medico = c.id_medico
JOIN especialidad e ON e.id_especialidad = me.id_especialidad
JOIN estado_cita ec ON ec.id_estado = c.id_estado
GROUP BY CUBE (e.nombre, ec.codigo)
ORDER BY especialidad, estado');

    
        
COMMIT;

END;