
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 08:29:56 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.api.consultas',
      p_base_path      => '/api/consultas/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.consultas',
      p_pattern        => 'resumen',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.consultas',
      p_pattern        => 'resumen',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT con.id_consulta,
       con.fecha_atencion,
       JSON_VALUE(con.anamnesis, ''$.motivoPrincipal'') AS motivo_principal
FROM consulta con
WHERE con.anamnesis IS NOT NULL
ORDER BY con.id_consulta');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.consultas',
      p_pattern        => 'create',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.consultas',
      p_pattern        => 'create',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_body         CLOB := :body_text;
    l_id_consulta  NUMBER;
BEGIN
    sp_registrar_consulta(
        p_id_cita              => JSON_VALUE(l_body, ''$.id_cita'' RETURNING NUMBER),
        p_motivo_consulta      => JSON_VALUE(l_body, ''$.motivo_consulta''),
        p_enfermedad_actual    => JSON_VALUE(l_body, ''$.enfermedad_actual''),
        p_examen_fisico        => JSON_VALUE(l_body, ''$.examen_fisico''),
        p_plan_tratamiento     => JSON_VALUE(l_body, ''$.plan_tratamiento''),
        p_anamnesis            => JSON_QUERY(l_body, ''$.anamnesis'' RETURNING CLOB),
        p_nlp_entidades        => JSON_QUERY(l_body, ''$.nlp_entidades'' RETURNING CLOB),
        p_presion_sistolica    => JSON_VALUE(l_body, ''$.presion_sistolica'' RETURNING NUMBER),
        p_presion_diastolica   => JSON_VALUE(l_body, ''$.presion_diastolica'' RETURNING NUMBER),
        p_frec_cardiaca        => JSON_VALUE(l_body, ''$.frec_cardiaca'' RETURNING NUMBER),
        p_frec_respiratoria    => JSON_VAL' || 'UE(l_body, ''$.frec_respiratoria'' RETURNING NUMBER),
        p_temperatura          => JSON_VALUE(l_body, ''$.temperatura'' RETURNING NUMBER),
        p_saturacion_o2        => JSON_VALUE(l_body, ''$.saturacion_o2'' RETURNING NUMBER),
        p_peso_kg              => JSON_VALUE(l_body, ''$.peso_kg'' RETURNING NUMBER),
        p_talla_cm             => JSON_VALUE(l_body, ''$.talla_cm'' RETURNING NUMBER),
        p_codigo_cie_principal => JSON_VALUE(l_body, ''$.codigo_cie_principal''),
        p_observacion_diag     => JSON_VALUE(l_body, ''$.observacion_diag''),
        p_id_consulta          => l_id_consulta
    );

    :status_code := 201;

    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Content-Type: application/json'');
    OWA_UTIL.http_header_close;

    HTP.prn(
        JSON_OBJECT(
            ''mensaje'' VALUE ''Consulta registrada correctamente'',
            ''id_consulta'' VALUE l_id_consulta
        )
    );
END;');

    
        
COMMIT;

END;