
-- Generated by ORDS REST Data Services 24.1.0.r1080942
-- Schema: SISTEMAMEDICO  Date: Sat May 16 10:39:48 2026 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SISTEMAMEDICO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'medica',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'sistema.medico.api.citas',
      p_base_path      => '/api/citas/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-mes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-mes',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT TO_CHAR(TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), ''YYYY-MM'') AS mes,
       e.codigo AS estado,
       COUNT(*) AS total_citas
FROM cita c
JOIN estado_cita e ON e.id_estado = c.id_estado
GROUP BY ROLLUP (TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), e.codigo)
ORDER BY mes, estado');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-estado',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'citas-estado',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'WITH base AS (
  SELECT TO_CHAR(TRUNC(CAST(c.fecha_hora AS DATE), ''MM''), ''YYYY-MM'') AS mes,
         e.codigo AS estado
  FROM cita c
  JOIN estado_cita e ON e.id_estado = c.id_estado
)
SELECT *
FROM base
PIVOT (
  COUNT(*) FOR estado IN (
    ''PROGRAMADA'' AS programada,
    ''ATENDIDA'' AS atendida,
    ''CANCELADA'' AS cancelada
  )
)
ORDER BY mes');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'create',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'create',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_body     CLOB := :body_text;
    l_id_cita  NUMBER;
BEGIN
    sp_registrar_cita(
        p_id_paciente      => JSON_VALUE(l_body, ''$.id_paciente'' RETURNING NUMBER),
        p_id_medico        => JSON_VALUE(l_body, ''$.id_medico'' RETURNING NUMBER),
        p_id_consultorio   => JSON_VALUE(l_body, ''$.id_consultorio'' RETURNING NUMBER),
        p_codigo_estado    => JSON_VALUE(l_body, ''$.codigo_estado''),
        p_fecha_hora       => TO_TIMESTAMP(JSON_VALUE(l_body, ''$.fecha_hora''), ''YYYY-MM-DD HH24:MI:SS''),
        p_duracion_min     => JSON_VALUE(l_body, ''$.duracion_min'' RETURNING NUMBER),
        p_motivo_solicitud => JSON_VALUE(l_body, ''$.motivo_solicitud''),
        p_id_cita          => l_id_cita
    );

    :status_code := 201;

    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Content-Type: application/json'');
    OWA_UTIL.http_header_close;

    HTP.prn(
        JSON_OBJECT(
            ''mensaje'' VALUE ''Cita registrada correctamente''' || ',
            ''id_cita'' VALUE l_id_cita
        )
    );
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'update',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'update',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_body CLOB := :body_text;
BEGIN
    sp_actualizar_cita(
        p_id_cita          => JSON_VALUE(l_body, ''$.id_cita'' RETURNING NUMBER),
        p_id_paciente      => JSON_VALUE(l_body, ''$.id_paciente'' RETURNING NUMBER),
        p_id_medico        => JSON_VALUE(l_body, ''$.id_medico'' RETURNING NUMBER),
        p_id_consultorio   => JSON_VALUE(l_body, ''$.id_consultorio'' RETURNING NUMBER),
        p_codigo_estado    => JSON_VALUE(l_body, ''$.codigo_estado''),
        p_duracion_min     => JSON_VALUE(l_body, ''$.duracion_min'' RETURNING NUMBER),
        p_motivo_solicitud => JSON_VALUE(l_body, ''$.motivo_solicitud'')
    );

    :status_code := 200;

    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Content-Type: application/json'');
    OWA_UTIL.http_header_close;

    HTP.prn(
        JSON_OBJECT(
            ''mensaje'' VALUE ''Cita actualizada correctamente''
        )
    );
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'delete',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'delete',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_body CLOB := :body_text;
BEGIN
    sp_eliminar_cita(
        p_id_cita => JSON_VALUE(l_body, ''$.id_cita'' RETURNING NUMBER)
    );

    :status_code := 200;

    OWA_UTIL.mime_header(''application/json'', FALSE);
    HTP.p(''Content-Type: application/json'');
    OWA_UTIL.http_header_close;

    HTP.prn(
        JSON_OBJECT(
            ''mensaje'' VALUE ''Cita eliminada correctamente''
        )
    );
END;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'detalle',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sistema.medico.api.citas',
      p_pattern        => 'detalle',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT c.id_cita,
       TO_CHAR(c.fecha_hora, ''DD Mon, HH24:MI'', ''NLS_DATE_LANGUAGE=SPANISH'') AS fecha_hora,
       pp.nombres || '' '' || pp.apellidos AS paciente,
       pm.nombres || '' '' || pm.apellidos AS medico,
       co.codigo AS consultorio,
       e.nombre AS especialidad,
       ec.codigo AS estado
FROM cita c
JOIN persona pp ON pp.id_persona = c.id_paciente
JOIN persona pm ON pm.id_persona = c.id_medico
JOIN consultorio co ON co.id_consultorio = c.id_consultorio
JOIN medico_especialidad me ON me.id_medico = c.id_medico
JOIN especialidad e ON e.id_especialidad = me.id_especialidad
JOIN estado_cita ec ON ec.id_estado = c.id_estado
ORDER BY c.fecha_hora DESC');

    
        
COMMIT;

END;